# Generated by Django 4.0.2 on 2022-04-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_addbook_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbook',
            name='img',
        ),
    ]
