# Generated by Django 4.0.2 on 2022-04-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_addbook_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='imghub/'),
        ),
    ]
