# Generated by Django 4.0.2 on 2022-04-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_addbook_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbook',
            name='id',
        ),
        migrations.AlterField(
            model_name='addbook',
            name='bookid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
