# Generated by Django 4.0.2 on 2022-04-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_addbook_id_alter_addbook_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='bookid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
