# Generated by Django 4.0.2 on 2022-04-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_addbook_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='bookid',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
