# Generated by Django 4.0.2 on 2022-04-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_addbook_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='bookid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
