# Generated by Django 4.0.2 on 2022-04-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_addbook_bookid'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='email',
            field=models.EmailField(default='john@gmail.com', max_length=254),
        ),
    ]
