# Generated by Django 4.0.2 on 2022-04-25 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_addbook_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewbook',
            fields=[
                ('bookid', models.AutoField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=20)),
                ('email', models.EmailField(default='john@gmail.com', max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='imghub/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
