# Generated by Django 4.0.2 on 2022-04-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_viewbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='viewbook',
        ),
    ]
