# Generated by Django 4.0.2 on 2022-04-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_viewbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='price',
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
