# Generated by Django 4.0.2 on 2022-04-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_addbook_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbook',
            name='subject',
        ),
        migrations.AddField(
            model_name='addbook',
            name='Description',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='addbook',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
